### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Murest7** [ulyngs/open-source-no-distractions-for-youtube#11]
Would be awesome if you added the features (iPadOS Youtube Extension) that would make it possible to remove these:
- Explore button
- More from Youtube 
- Subscriptions 

Thank you in advance!
Regards, Maksim.

**Comment by ulyngs** [comment]
Good suggestion! 

I think this will have to come a little further down the line, because I think many users would not want these to always be hidden by default.

I think the right solution is to add a menu page where people can set what the defaults should be (#7), but it'll take me a while to figure out how to do this, so it probably won't be until the autumn where I should have a bit more time!

**Comment by ulyngs** [comment]
I should be able to add this to the next version, now that v3.0 adds the ability to save app settings

**Comment by ulyngs** [comment]
@Murest7 This is just to let you know that I just submitted an update to the App Store which will add your suggested features to the Mac version! It should be out in a day or two.

Will have a look at the iOS version later! :)
