### ISSUE TITLE
Request for a new feature + Bug

### ISSUE THREAD

**Issue by jdmracer1986** [ulyngs/open-source-no-distractions-for-youtube#13]
Hello,

I really wanted to reduce the amount of time I spent on youtube but I couldn't find an app similar to unhook.app for iPhone until I found yours so I am very glad .

The reason why most people download apps that limit their usage of addictive and time consuming apps is to obviously reduce the amount of time they spend on those apps but also because they feel that they cannot control themselves to stop/reduce using these apps by themselves.

I think I know a potential feature that could improve the goal of limiting distractions on YouTube.

Right now when you open youtube with the app installed and turned on the home page is blank with no videos I think this is good but still ineffective because the option to toggle on or off "Recommended videos" and "Up next videos" still exists.
"You can't lock yourself out if you still have the key."

I propose a feature that will remove the ability to toggle "Recommended videos" and "Up next videos" on or off as an option for people that would like to limit even more of their watch time.

Possibly from the app because it is too easy to click on the extensions bar and just toggle off the restrictions.

![2BBD506F-E204-4B93-9A38-B2FF9E4C89F4](https://user-images.githubusercontent.com/104505403/165524285-4b4b9f89-c3d8-4e94-887f-ad8f29e6a34c.jpeg)
![AB1FF21B-87AF-47C3-9DF6-DB4A8230F906](https://user-images.githubusercontent.com/104505403/165524295-80fad844-7d14-4060-abce-c3536b23cbc3.jpeg)

^This is basically what I am suggesting

I think this could be a good feature and many other of the users will agree with me because it adds to the purpose of this app
 
 As for the Bug, it seems like after this last update with the shorts the option to toggle on or off "Up next videos" has been replaced with the "shorts" option
![2178F306-12E5-4BED-9A4C-14AE3BA2BAD2](https://user-images.githubusercontent.com/104505403/165525411-01575bb1-d3dd-4e97-92ce-5fac69b30c9c.jpeg)
![5546E6B5-45B6-486C-9275-2F3023AF3A0A](https://user-images.githubusercontent.com/104505403/165525420-efefbda8-290a-4e3e-90c3-fc47b2acb779.jpeg)

Thank you for reading this.

**Comment by ulyngs** [comment]
Thanks for flagging this!

I'll fix the bug in the next update.

In terms of removing the toggles for a "can't be bypassed"-experience, I'm not entirely how best to do this because different users might want to hide different things before having it 'frozened'. 

I could certainly just do one simple version that I then submit as a second app to the app store, where people don't have any options to set the settings. The better option would be to make an actual sophisticated version where people set the option and then are made unable to change it, perhaps until they've typed in a very long password (Cold Turkey Blocker-style). However, this goes beyond my macOS and iOS coding ability... 

Let me have a think!

**Comment by ulyngs** [comment]
Fixed the missing 'up next' toggle on mobile w 9e97c3c816f1b7b28165421acfc75f0a2311ff90

**Comment by jdmracer1986** [comment]
Thanks for responding!
