### ISSUE TITLE
Safari on macOS does not seem to save settings

### ISSUE THREAD

**Issue by yueqianh** [ulyngs/open-source-no-distractions-for-youtube#14]
It seems that the extension does not save my settings in the latest Safari build 15.5. When a new YouTube tab is opened, the comments are hidden even though I have previously enabled the comments.

**Comment by ulyngs** [comment]
Thanks for flagging this: At the moment, this is actually not a bug, but a design choice! It's on purpose that you will need to re-toggle the comments on every time, so that there is a bit of friction to do something that might otherwise become a distraction! :)

I am planning, however, to add the option to choose whether or not the app should remember or forget the settings (see #7).  It would take quite a bit of time for me to figure out how to this, however, because Apple's documentation for Safari Extensions is pretty awful! :(

**Comment by tadaspetra** [comment]
Adding a bit of support to this thread, as. I would love this feature. I feel like comments can be informative in case there's updates to a tutorial or something. 

And personally I don't find myself wasting much time in there unless necessary, so would be awesome to have it save :) 

Great work on this!

**Comment by ulyngs** [comment]
Okay, so this is indeed quite a common request (also #17).

The only challenge is just one of my personal time, because I'm super swamped -- I can probably create this ability in the spring, stay tuned!

**Comment by ulyngs** [comment]
I've (finally!) added this to the version 3.0 that I just submitted to the app store -- it should be available in a day or two, let me know what you think!!

**Comment by tadaspetra** [comment]
Yes it works great! Thank you 💯
