### ISSUE TITLE
Add friction / delay to changing settings

### ISSUE THREAD

**Issue by bbv99** [ulyngs/open-source-no-distractions-for-youtube#23]
I have used your safari extension for a while now and it works great for me :) I have two suggestions which would make the extention even better in my opinion:

- The ability to hide shorts from the subscriptions feed
- Remove the extension icon from the toolbar. Move the options to the app

**Comment by ulyngs** [comment]
I think these are great ideas! I have just submitted an update to the app store that adds the ability for the app to remember your preferred settings -- I do agree that it might be preferable to have the toggles live in the app rather than in the extension icon, to add a little extra friction to change the settings (especially now that the app can remember your preferences).

I will put your suggestions on the suggestions for the next update! :)

**Comment by OscarPalafox** [comment]
Just wanted to chime in, and +1 the idea of moving the setting to the app to add some friction. It would be great!

**Comment by ulyngs** [comment]
I see that this would address a need of added friction for *some* users, but I am unsure about whether the added friction is something that all users want.

Maybe the alternative solution is an option to an optional five-second wait time to change the settings, instead of forcing everyone to open the app to toggle settings on or off?

**Comment by OscarPalafox** [comment]
I think this could be an interesting idea, but it's not necessarily incompatible with hiding the settings behind the app, and I feel like 5s might be too short (maybe being able to customize this would be even better). I'm thinking an interesting alternative could be to add a toggle in the app to show/not show the settings within Safari. This toggle could be off by default so that users would need to manually enable this. I don't know whether that's possible, but I think it would solve the issue for both kind of users.

To be fair, supporting this toggle for showing the setting in the app and Safari seems like it might be quite some work, and I think adding a delay is a great way of adding some friction.

**Comment by ulyngs** [comment]
I'm imagining now something like a checkbox that says "add delay to adjusting the settings" and then a "wait ____ seconds before showing the settings" where you can type the number of seconds

**Comment by ulyngs** [comment]
I'll update the app with something like this as a starting point -- let me know if it works as you hoped!

<img width="213" alt="image" src="https://user-images.githubusercontent.com/23137032/222475148-32f5b3bd-a92b-41eb-b788-d29400fa22cd.png">

**Comment by ulyngs** [comment]
Update submitted, it should be out in a day or so, let me know what you think!
